<?php

define('FEED_MERGER_DEFAULT_URL', 'http://example.net/rss.xml');
define('FEED_MERGER_PASSWORD_MIN_SIZE', 6);

//TODO interface avec feedburner (cf module feedburner)
//TODO créer le content-type 'feed' dans le module + la view aussi (utiliser module 'feature' pour exporter tout ça ?)
//TODO utiliser job_scheduler pour scheduler le bouzin ?
//TODO hardening => supprimer dépendances de modules inutiles
//TODO watchdog
//TODO have feeds published on a Twitter account

/**
 * Implementation of hook_theme
 */
function feed_merger_theme() {
  return array(
    'feed_merger_items_email' => array(
      'template' => 'templates/feed-items-email',
      'variables' => array('feeds' => NULL)
    )
  );
}

/**
 * Returns the list the user has subscribed to
 * @return array of feeds
 */
function _feed_merger_get_feeds($uid) {
  global $user;
  $feeds = entity_load('node', FALSE, array(
    'type' => 'feed',
    'uid' => $user->uid,
  ));
  return $feeds;
}

/**
 * Determines whether the user has subscribed to a feedURL
 * @param feedURL feed URL
 * @return TRUE if the user has subscribed to the feed ; FALSE if not
 */
function _feed_merger_user_has_feed($feedURL) {
  global $user;
  $query = new EntityFieldQuery();
  $countFeeds = $query->entityCondition('entity_type', 'node')
  ->propertyCondition('type', array('feed'))//TODO can we remove the array ?
  ->propertyCondition('uid', $user->uid)
  ->fieldCondition('field_link', 'url', $feedURL)
  ->count()
  ->execute();
  return !empty($countFeeds);
}

function _feed_merger_get_feed_items($feed) {
  $xmlUrl = $feed->field_url[LANGUAGE_NONE][0]['url'];
  $xmlData = drupal_http_request($xmlUrl)->data;
  $xmlObject = simplexml_load_string($xmlData);
  //TODO controle XML bien formé ? voir si fourni dans simplexml
  $feedItems = array();
  $feedTitle = (string) $xmlObject->channel->title;
  foreach($xmlObject->channel->item as $item) {
    $feedItems[] = array(
      'feedTitle' => $feedTitle,
      'title' => (string) $item->title,
      'link' => (string) $item->link,
      'description' => (string) $item->description,
      'pubDate' => format_date(strtotime($item->pubDate), 'custom', 'D, d/m/Y H:i'),
    );
  }
  //TODO vérifier specs RSS + autres types de feeds
  return $feedItems;
}

/**
 * Implementation of hook_mail
 */
function feed_merger_mail($key, &$message, $params) {
  switch($key) {
    case 'feed_items':
      $message['subject'] = t('Feeds for @username - @datetime', array(
        '@username' => $params['user']->name,
        '@datetime' => format_date(time(), 'custom', 'd/m/Y - H:i'),
      ));
      $message['body'][] = $params['feed_items'];
      break;
  }
}

//TODO US-formatted dates when using format_date + the browser is US

/**
 * Implementation of hook_mail_alter
 */
function feed_merger_mail_alter(&$message) {
  $headers = array(
    'MIME-Version' => '1.0',
    'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
    'Content-Transfer-Encoding' => '8Bit',
    'X-Mailer' => 'Drupal'
  );
  foreach($headers as $key=>$value) {
    $message['headers'][$key] = $value;
  }
}

/**
 * Implementation of hook_cron
 */
function feed_merger_cron() {
  $accounds = entity_load('user');
  foreach($accounts as $account) {
    $feedNodes = _feed_merger_get_feeds();
    if(!empty($feedNodes)) { //TODO watchdog si $feeds is empty ?
      $feeds = array();
      foreach($feedNodes as $feedNode) {
        $feeds[$feedNode->nid] = array(
          'title' => $feedNode->title,//TODO sanitize title ? XSS
          'items' => _feed_merger_get_feed_items($feedNode),
        );
      }
      $output = theme('feed_merger_items_email', array('feeds' => $feeds));
      drupal_mail('feed_merger', 'feed_items', $account->mail, language_default(), array(
        'feed_items' => $output,
        'user' => $account
      ));
    }
    //TODO sort feedItems par pubDate
    //TODO check_xss dans un preprocess ? (cf drupal.org/node/933976)
  }
}

//TODO permettre de choisir d'afficher seulement le titre, d'ajouter un summary au début, de trier par date ou par source

/**
 *  Implementation of hook_enable
 */
function feed_merger_enable() {
  //HTML implementation of MailSystem to be used when sending mails from this module
  $mailSystem = variable_get('mail_system', array('default-system' => 'DefaultMailSystem'));
  $mailSystem = array_merge($mailSystem, array('feed_merger' => 'HTMLMailSystem'));
  variable_set('mail_system', $mailSystem);
}

/**
 * Implementation of hook_disable
 */
function feed_merger_disable() {
  //Remove use of HTML implementation of MailSystem from this module
  $mailSystem = variable_get('mail_system', array('default-system' => 'DefaultMailSystem'));
  unset($mailSystem['feed_merger']);
  variable_set('mail_system', $mailSystem);
}

/**
 * Implementation of hook_node_validate
 */
function feed_merger_node_validate($node, $form, &$form_state) {
  if($node->type == 'feed') {
    $feedURL = $node->field_link[LANGUAGE_NONE][0]['url'];
    if(_feed_merger_user_has_feed($feedURL)) {
      form_set_error('url', t('Feed %url is already in your list. ', array('%url' => $feedURL)));
    }
  }
}

//TODO mettre une UI pour fixer la langue de l'utilisateur lors de son inscription
//TODO unsubscribe link (footer of mail)
//TODO define 'feed' content type in this module

function _feed_merger_add_form_validate($form, $form_state) {
  //TODO sanitize/normalize user input (ex. user enters URL wihout leading http -> use module canonical_url / nodewords)
  if(isset($form['email']) && !filter_var($form_state['values']['email'], FILTER_VALIDATE_EMAIL)) {
    form_set_error('email', t('Invalid email address.'));
  }
  if(isset($form['password']) && mb_strlen($form_state['values']['password']) < FEED_MERGER_PASSWORD_MIN_SIZE) {
    form_set_error('password', t('Password size should have at least @pwd-size characters.', array('@pwd-size' => FEED_MERGER_PASSWORD_MIN_SIZE)));
  }
  $feedURL = $form_state['values']['url'];
  try {
    Feed::loadRss($feedURL);
  } catch(Exception $e) {
    form_set_error('url', t('Invalid URL. Are you sure %url points to an RSS feed ?', array('%url' => $feedURL)));
  }
}

/**
 * Check if a user already have this email. Create a user if not. Log in the user.
 * @email email
 * @password password
 */
function _feed_merger_create_login_user($email, $password) {
//TODO if user is not logged in => create an account if necessary + open up session
  $account = user_load_by_mail($email);
  if(!$account) {
    //TODO create user
  }
  $uid = user_authenticate($account->name, $password);//TODO apply email as username and simplify this piece of code
  
}

function _feed_merger_add_form_submit($form, &$form_state) {
  $feedURL = $form_state['values']['url'];
  if(isset($form_state['values']['email'])) {
    $email = $form_state['values']['email'];
    $password = $form_state['values']['password'];
    _feed_merger_create_login_user($email, $password);
  }
  global $user;
  $feedNode = new StdClass();
  $feedNode->uid = $user->uid;
  $feedNode->type = 'feed';
  $feedNode->title = Feed::loadRss($feedURL)->title;
  $feedNode->field_link[LANGUAGE_NONE][]['url'] = $feedURL;
  node_object_prepare($feedNode);
  node_validate($feedNode, $form, $form_state);
  $errors = form_get_errors();
  if(empty($errors)) {
    node_save($feedNode);
    drupal_set_message(t('Successfully added %url to your feed list.', array('%url' => $feedURL)));
  }
}

function _feed_merger_add_form() {
  //TODO check anti-CSRF token here
  $form['url'] = array(
    '#type' => 'textfield',
    '#default_value' => FEED_MERGER_DEFAULT_URL,
  );
  global $user;
  if($user->uid == 0) {
    $form['email'] = array(
      '#type' => 'textfield',
      '#title' => t('Email'),
    );
    $form['password'] = array(
      '#type' => 'password',
      '#title' => t('Password'),
    );
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Add to my feed list'),
  );
  //TODO checkbox 'remember me'
  return $form;
}

//TODO below feeds list: add checkbox "send me a daily digest when my feeds get updated"
