<?php

define('FEED_MERGER_DEFAULT_URL', 'http://example.net/rss.xml');
define('FEED_MERGER_HOME_PATH', 'feeds');

//TODO interface avec feedburner (cf module feedburner)
//TODO créer le content-type 'feed' dans le module + la view aussi (utiliser module 'feature' pour exporter tout ça ?)
//TODO utiliser job_scheduler pour scheduler le bouzin ?
//TODO hardening => supprimer dépendances de modules inutiles
//TODO watchdog
//TODO have feeds published on a Twitter account

/**
 * Implementation of hook_theme
 */
function feed_merger_theme() {
  return array(
    'feed_merger_items_email' => array(
      'template' => 'templates/feed-items-email',
      'variables' => array('feeds' => NULL)
    )
  );
}

/**
 * Returns the list the user has subscribed to
 * @return array of feeds
 */
function _feed_merger_get_feeds($uid) {
  global $user;
  $feeds = entity_load('node', FALSE, array(
    'type' => 'feed',
    'uid' => $user->uid,
  ));
  return $feeds;
}

/**
 * Determines whether the user has subscribed to a feedURL
 * @param feedURL feed URL
 * @return TRUE if the user has subscribed to the feed ; FALSE if not
 */
function _feed_merger_user_has_feed($feedURL) {
  global $user;
  $query = new EntityFieldQuery();
  $countFeeds = $query->entityCondition('entity_type', 'node')
  ->propertyCondition('type', array('feed'))//TODO can we remove the array ?
  ->propertyCondition('uid', $user->uid)
  ->fieldCondition('field_link', 'url', $feedURL)
  ->count()
  ->execute();
  return !empty($countFeeds);
}

function _feed_merger_get_feed_items($feed) {
  $xmlUrl = $feed->field_url[LANGUAGE_NONE][0]['url'];
  $xmlData = drupal_http_request($xmlUrl)->data;
  $xmlObject = simplexml_load_string($xmlData);
  //TODO controle XML bien formé ? voir si fourni dans simplexml
  $feedItems = array();
  $feedTitle = (string) $xmlObject->channel->title;
  foreach($xmlObject->channel->item as $item) {
    $feedItems[] = array(
      'feedTitle' => $feedTitle,
      'title' => (string) $item->title,
      'link' => (string) $item->link,
      'description' => (string) $item->description,
      'pubDate' => format_date(strtotime($item->pubDate), 'custom', 'D, d/m/Y H:i'),
    );
  }
  //TODO vérifier specs RSS + autres types de feeds
  return $feedItems;
}

/**
 * Implementation of hook_mail
 */
function feed_merger_mail($key, &$message, $params) {
  switch($key) {
    case 'feed_items':
      $message['subject'] = t('Feeds for @username - @datetime', array(
        '@username' => $params['user']->name,
        '@datetime' => format_date(time(), 'custom', 'd/m/Y - H:i'),
      ));
      $message['body'][] = $params['feed_items'];
      break;
  }
}

//TODO US-formatted dates when using format_date + the browser is US

/**
 * Implementation of hook_mail_alter
 */
function feed_merger_mail_alter(&$message) {
  $headers = array(
    'MIME-Version' => '1.0',
    'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
    'Content-Transfer-Encoding' => '8Bit',
    'X-Mailer' => 'Drupal'
  );
  foreach($headers as $key=>$value) {
    $message['headers'][$key] = $value;
  }
}

/**
 * Implementation of hook_cron
 */
function feed_merger_cron() {
  $accounds = entity_load('user');
  foreach($accounts as $account) {
    $feedNodes = _feed_merger_get_feeds();
    if(!empty($feedNodes)) { //TODO watchdog si $feeds is empty ?
      $feeds = array();
      foreach($feedNodes as $feedNode) {
        $feeds[$feedNode->nid] = array(
          'title' => $feedNode->title,//TODO sanitize title ? XSS
          'items' => _feed_merger_get_feed_items($feedNode),
        );
      }
      $output = theme('feed_merger_items_email', array('feeds' => $feeds));
      drupal_mail('feed_merger', 'feed_items', $account->mail, language_default(), array(
        'feed_items' => $output,
        'user' => $account
      ));
    }
    //TODO sort feedItems par pubDate
    //TODO check_xss dans un preprocess ? (cf drupal.org/node/933976)
  }
}

//TODO permettre de choisir d'afficher seulement le titre, d'ajouter un summary au début, de trier par date ou par source

/**
 *  Implementation of hook_enable
 */
function feed_merger_enable() {
  //HTML implementation of MailSystem to be used when sending mails from this module
  $mailSystem = variable_get('mail_system', array('default-system' => 'DefaultMailSystem'));
  $mailSystem = array_merge($mailSystem, array('feed_merger' => 'HTMLMailSystem'));
  variable_set('mail_system', $mailSystem);
}

/**
 * Implementation of hook_disable
 */
function feed_merger_disable() {
  //Remove use of HTML implementation of MailSystem from this module
  $mailSystem = variable_get('mail_system', array('default-system' => 'DefaultMailSystem'));
  unset($mailSystem['feed_merger']);
  variable_set('mail_system', $mailSystem);
}

/**
 * Implementation of hook_node_validate
 */
function feed_merger_node_validate($node, $form, &$form_state) {
  if($node->type == 'feed') {
    $feedURL = $node->field_link[LANGUAGE_NONE][0]['url'];
    if(_feed_merger_user_has_feed($feedURL)) {
      form_set_error('url', t('Feed %url is already in your list. ', array('%url' => $feedURL)));
    }
  }
}

//TODO mettre une UI pour fixer la langue de l'utilisateur lors de son inscription
//TODO unsubscribe link (footer of mail)
//TODO define 'feed' content type in this module

/*****************************************************************************************
 * 'Add feed' form
 *****************************************************************************************/

function _feed_merger_add_feed_form_validate($form, $form_state) {
  //TODO sanitize/normalize user input (ex. user enters URL wihout leading http -> use module canonical_url / nodewords)
  $feedURL = $form_state['values']['url'];
  try {
    Feed::loadRss($feedURL);
  } catch(Exception $e) {
    form_set_error('url', t('Invalid feed %url', array('%url' => $feedURL)));
  }
}

function _feed_merger_add_feed_form_submit($form, &$form_state) {
  $feedURL = $form_state['values']['url'];
  global $user;
  $feedNode = new StdClass();
  $feedNode->uid = $user->uid;
  $feedNode->type = 'feed';
  $feedNode->title = Feed::loadRss($feedURL)->title;
  $feedNode->field_link[LANGUAGE_NONE][]['url'] = $feedURL;
  node_object_prepare($feedNode);
  node_validate($feedNode, $form, $form_state);
  $errors = form_get_errors();
  if(empty($errors)) {
    node_save($feedNode);
    drupal_set_message(t('Successfully added %url to your feed list.', array('%url' => $feedURL)));
  }
}

function _feed_merger_add_feed_form() {
  //TODO check anti-CSRF token here
  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => t('Feed URL'),
    '#default_value' => FEED_MERGER_DEFAULT_URL,
    '#weight' => -10,
  );
  $form['actions'] = array(
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Add to my feed list'),
    )
  );
  return $form;
}

/*****************************************************************************************
 * 'Login and add feed' form
 *****************************************************************************************/
function _feed_merger_login_add_feed_form_validate($form, $form_state) {
  /*
  if(!filter_var($form_state['values']['email'], FILTER_VALIDATE_EMAIL)) {
    form_set_error('email', t('Invalid email address.'));
  }
  if(mb_strlen($form_state['values']['password']) < FEED_MERGER_PASSWORD_MIN_SIZE) {
    form_set_error('password', t('Password size should have at least @pwd-size characters.', array('@pwd-size' => FEED_MERGER_PASSWORD_MIN_SIZE)));
  }
  */
  //drupal_validate_form('_feed_merger_add_feed_form', $form, $form_state);FIXME this line should be required
}

//TODO if user changes his email address then synchronize email with name (hook_node_alter)
//TODO install module 'email registration'

function _feed_merger_login_add_feed_form_submit($form, &$form_state) {
  //TODO sanitize input values (trim+XSS safe) : email/pwd
  $email = $form_state['values']['email'];
  $password = $form_state['values']['password'];
  if(!user_load_by_mail($email)) {
    //user does not exist -> register user
    $register_form_state['values']['name'] = $email;
    $register_form_state['values']['mail'] = $email;
    $register_form_state['values']['pass']['pass1'] = $password;
    $register_form_state['values']['pass']['pass2'] = $password;
    $register_form_state['values']['op'] = t('Create new account');//FIXME is that actually necessary ?
    drupal_form_submit('user_register_form', $register_form_state);//FIXME test this !
  }
//authenticate user
$login_form_state['values']['name'] = $email;
$login_form_state['values']['pass'] = $password;
drupal_form_submit('user_login', $login_form_state);//TODO what if authentication fails ?
//add submitted URL to feed list
drupal_form_submit('_feed_merger_add_feed_form', $form_state);
//redirect to home destination page
drupal_goto();
}

function _feed_merger_login_add_feed_form() {
  //TODO check CSRF here
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#required' => TRUE,
  );
  $form['password'] = array(
    '#type' => 'password',
    '#title' => t('Password'),
    '#required' => TRUE,
  );
  return array_merge($form, _feed_merger_add_feed_form());
}

//TODO below feeds list: add checkbox "send me a daily digest when my feeds get updated" (module 'persistent login')
//TODO login using Twitter

/**
 * Implementation of hook_block_info
 */
function feed_merger_block_info() {
  $blocks[0] = array(
    'info' => 'Add to my feed list',
    'cache' => DRUPAL_NO_CACHE,
    //TODO define block visibility here
  );
  $blocks[1] = array(
    'info' => 'Login and add to my feed list',
    'cache' => DRUPAL_NO_CACHE,
    //TODO define block visibility here
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view
 */
function feed_merger_block_view($delta = '') {
  switch($delta) {
    case 0:
      return array(
        'subject' => NULL,
        'content' => drupal_get_form('_feed_merger_add_feed_form'),
      );
    case 1:
      return array(
        'subject' => NULL,
        'content' => drupal_get_form('_feed_merger_login_add_feed_form'),
      );
  }
}

